version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=database
      - DB_USER=ROOT
      - DB_PASSWORD=12345678
      - DB_NAME=project_3
      - DB_PORT=3306
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_AUTHENTICATION_PLUGIN=caching_sha2_password # Set the authentication plugin
    restart: unless-stopped

  database:
    build:
      context: ./database
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: project_3
      MYSQL_ROOT_HOST: "%" # Allow root connections from any host
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
